### ISSUE TITLE
Why not use microsoft-edge protocol?

### ISSUE THREAD

**Issue by Alovchin91** [MicrosoftEdge/MicrosoftEdgeLauncher#4]
It's more of a question rather than an issue. What are the use cases for this tool that cannot be covered by **microsoft-edge** protocol? For example, you could use the following command instead:
`start microsoft-edge://bing.com`

**Comment by spiderwebwoman** [comment]
One use case is to add Edge to the list of browsers you can preview your web pages in using Expression Web. Adding the .exe located at C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe doesn't work.

**Comment by andysterland** [comment]
The main motivation is that some programs like Visual Studio require an exe that can be started via CreateProcess so they need an 'old school' exe.

**Comment by rmullaney77** [comment]
For anyone else who wanders in here looking to get around the same issue, `start microsoft-edge:` will not open local files. After a minor modification to the C# source (below), this solution does exactly what I needed.

Note: Simplified RegEx since it failed on modern TLDs, IP notation and was restricted to "http" protocol. Figure if it starts with a valid protocol, send it. If not, prepend "file://" then sent it. Leave providing a valid URL/path up to the end-user (in this case, me) 🤣

```
//check, if valid URL
var regex = new Regex(@"^(https?|ftp)\://.*$");
if (!regex.IsMatch(url))
	//assume local file
	url = "file://" + url;
launcher.ActivateApplication(EdgeName, url, ActivateOptions.None, out pid);
break;
```

Can FINALLY launch Edge from my Dreamweaver CS5's "Preview in Browser" list! 😁
